name: CICD

'on':
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: bioconductor/bioconductor_docker:RELEASE_3_11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Prelim Package Dependencies
        run: Rscript -e "BiocManager::install(c('remotes', 'rcmdcheck', 'covr', 'pkgdown', 'renv', 'BiocStyle'))"
      - name: Set up cache
        uses: actions/cache@v1
          with:
            path: ~/.local/share/renv
            key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
            restore-keys: |
              ${{ runner.os }}-renv-
      - name: Finish Installing Package Deps
        run: Rscript -e "remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())"
      - name: System dependencies
        run: |
          pip install ghp-import
      - name: Check Package
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check')"
      - name: Document Package
        run: |
          Rscript -e "pkgdown::build_site()"
      - name: Deploy to GitHub Pages
        if: github.ref == 'master'
        run: |
          ghp-import -n docs && \
          git push -qf https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages

